// Parkove version history. Newest first.
// Every update session: add an entry here and bump VERSION (+ package.json).

export const VERSION = '0.52.0'

export type ChangeType = 'added' | 'changed' | 'fixed'

export type Release = {
  version: string
  date: string
  title: string
  changes: Array<[ChangeType, string]>
}

export const CHANGELOG: Release[] = [
  {
    version: '0.52.0',
    date: '2026-08-21',
    title: 'Inter, and one card that says everything',
    changes: [
      ['changed', 'The text face is Inter instead of Manrope. Bricolage Grotesque still carries the headlines'],
      ['changed', 'The walk card now says the whole thing: what comes next, then under a hairline how long you have been walking, how far, and how many points you have. The pill at the top is gone, so a walk speaks from one place instead of two'],
      ['changed', 'The card breathes wider: 24 points of margin left and right instead of 16'],
      ['changed', 'The map layer and locate buttons stopped competing with the content. Dark glass instead of white tiles with a shadow, smaller, and they let the map through'],
      ['fixed', 'The map attribution sat under the Punkty label during a walk. It moves up while one is running'],
    ],
  },
  {
    version: '0.51.1',
    date: '2026-08-21',
    title: 'The walking HUD, gone over detail by detail',
    changes: [
      ['fixed', 'The three labels under the buttons sat at different heights, because the bigger middle button pushed its own label down. The buttons now share a baseline and the lime one rises above it'],
      ['fixed', 'The layers and locate buttons still overlapped the card, hiding the distance. They now sit above the whole HUD'],
      ['changed', 'The card is a button: touching it opens what it is talking about, the story of the next point when close and the place when far. It used to be the only tile on screen that looked tappable and did nothing'],
      ['changed', 'Press states everywhere: buttons sink and their glass brightens for a moment, the card sinks and tints, the lime one flares its ring. The lime ring also breathes slowly while a walk is running'],
      ['changed', 'The distance carries two weights, a bold number and a muted unit, the dashes are inset from the card edge and thicker with rounded ends, and the menu pills are fully oval'],
    ],
  },
  {
    version: '0.51.0',
    date: '2026-08-21',
    title: 'One HUD for a walk, down where the thumb is',
    changes: [
      ['changed', 'A walk used to speak from two places at once: the top card carried the name, the points and the next stop while the bottom bar carried the time and the distance. The top card is gone. What is left up there is a small mono pill with the time and the kilometres, clear of the menu it used to slide under'],
      ['changed', 'The bottom is one HUD: a card saying what comes next, with the progress as one dash per point, and three round buttons under it. The side ones are dark glass over the map rather than white discs, the middle one is lime and adds a memory'],
      ['changed', 'Far from a park the card stops naming a point you cannot reach and gives the way to the park instead. No compass and no rotating arrow: that would mean asking for the gyroscope and pretending to be a navigation app'],
      ['changed', 'The plus opens over the map now, not above it: three glass pills on a progressive blur with a darkened gradient, and a white round close underneath'],
    ],
  },
  {
    version: '0.50.0',
    date: '2026-08-21',
    title: 'Photographs on the points, boxes for the practical things',
    changes: [
      ['added', 'Sixty three points got a photograph from Wikimedia Commons, with the author and licence in the data. Points without one fell from 117 to 54, and the rest carry names we invented, which Commons does not have'],
      ['changed', 'The place card reordered: description, then the points, then the practical pair. Playground and food are two boxes side by side with a short status and a quiet chevron, instead of two rows of prose'],
      ['changed', 'Map pins speak one language now. The start screen wears the same dark disc, white ring and lime mark as a replay, so the same route no longer looks like two different apps. Parking says it in blue, same shape'],
      ['fixed', 'A pin size expression with zoom nested inside a multiplication silently killed the whole symbol layer: cafe and playground pins were rings with nothing in them'],
      ['fixed', 'Three places where Polish grammar counted wrong: 3 punktów, 6 miejsca, quest: 3 punktów'],
    ],
  },
  {
    version: '0.49.0',
    date: '2026-08-21',
    title: 'A list you can decide from, and a menu',
    changes: [
      ['changed', 'The places list sorts by how far it is from you instead of by the alphabet, groups into started, untouched and stamped, and carries a photograph of each place. Hectares are gone; the playground and coffee icons stay'],
      ['changed', 'Tapping a cafe or a playground now selects that one place: the map centres on it, the pin grows and gets a ring, and a card names it. It used to open a list and send you to Google'],
      ['changed', 'The profile icon at the top is a menu. Everything that used to be buried inside the profile now sits on one level, and the profile is one entry among them'],
    ],
  },
  {
    version: '0.48.1',
    date: '2026-08-21',
    title: 'Every point checked against the map',
    changes: [
      ['fixed', 'Two more points were in the wrong place. The Matejko monument was 459 metres from the monument, in the western Planty, while our own description said it stands between the Barbakan and the Florian Gate. Bukowe Skaly in Dolina Szklarki was 70 metres out'],
      ['changed', 'The Skawina oxbow moved a second time. My first correction was a guess at the park boundary nearest the water, and it was 102 metres from the oxbow the map actually knows by name'],
      ['added', 'The audit now checks all 136 points against OpenStreetMap by name inside each park. Seventy seven have a match and seventy six of them agree to within nine metres. The rest carry names we invented, so this method cannot judge them'],
    ],
  },
  {
    version: '0.48.0',
    date: '2026-08-21',
    title: 'Wrong pins moved to where the things actually are',
    changes: [
      ['fixed', 'Four points stood in the wrong place. The bathing pontoons at Zakrzowek were 760 metres north of the water, and in the Skawina park the old oak was out by 205 metres, the monument by 165 and the oxbow by 276. All four now sit on the object OpenStreetMap has'],
      ['added', 'A coordinate audit script. Without a network it lists the points typed by hand, which give themselves away by having three or four decimal places where anything taken from a map has five or six: 22 of 136 points. With a network it compares every point against the matching object in OSM'],
      ['changed', 'The valleys lost their public transport box. There is no city transport out there and the agglomeration line numbers were a guess, so each valley has a real parking from OSM instead, with the distance to the valley floor'],
    ],
  },
  {
    version: '0.47.0',
    date: '2026-08-21',
    title: 'All the valleys, and photographs of them',
    changes: [
      ['added', 'Four more valleys: Bedkowska with the highest waterfall in the Jura and its largest cave, Raclawki with a numbered nature trail across 474 hectares, Eliaszowki where the Carmelites named the springs after saints, and Szklarki with its tors. Seven valleys, 32 points'],
      ['added', 'Photographs. Every valley has a hero picture and seven points carry their own, all from Wikimedia Commons with the author and licence in the data. One arrived from a weir in a different region entirely and was thrown out'],
      ['changed', 'Szklarki asks for two points out of three, because only three things in it are catalogued by name'],
    ],
  },
  {
    version: '0.46.0',
    date: '2026-08-21',
    title: 'Dolinki Krakowskie, three of them',
    changes: [
      ['added', 'Three valleys outside the city: Dolina Kluczwody, Dolina Bolechowicka and Dolina Kobylanska, 14 to 16 km from the Main Square. Fifteen points between them, from the Brama Bolechowicka rock gate and a two-step waterfall to reconstructed partition border posts and a cholera cemetery'],
      ['added', 'The list of places has tabs: everything, the valleys, the city. A forty minute park and a half day trip are not the same outing'],
      ['added', 'A place can now ask for fewer points than it has. Each valley gives its stamp at three of five and keeps the rest as a reason to come back'],
      ['changed', 'Dodaj notatke on a walk card is Dodaj podsumowanie, because the note you write at home and the note you drop on the route are two different things'],
    ],
  },
  {
    version: '0.45.1',
    date: '2026-08-21',
    title: 'Walking the route again is a bar, not a row',
    changes: [
      ['changed', 'Przejdz te trase jeszcze raz left the scrolling card and took the bottom edge of the screen: a bar on its own glass, with a gradient the card dissolves into and the same three-band progressive blur the replay uses'],
    ],
  },
  {
    version: '0.45.0',
    date: '2026-08-21',
    title: 'Less on the walk card, one meaning for a stamp',
    changes: [
      ['changed', 'The walk card lost three of its five counters. Points, photos and notes were all listed a few centimetres further down the same screen, so only the time and the distance stayed'],
      ['changed', 'The empty note field no longer sits on every walk. There is a quiet Dodaj notatke instead, and the field appears when there is something to say'],
      ['changed', 'Photos, notes and recordings share one section, Co zostalo po drodze, in the order they happened. A photo and a voice note are the same kind of thing: something you stopped for'],
      ['fixed', 'A stamp meant two different things. The profile handed one out for showing up, while the ceremony after a walk only gave it for finishing a place. Now there is one rule, and a place may ask for fewer than all of its points, which is what a valley in the Jura will need'],
    ],
  },
  {
    version: '0.44.0',
    date: '2026-08-21',
    title: 'The percentage is gone',
    changes: [
      ['changed', 'No more percentage of Krakow. The ring and the number left the corner of the map, and the big number left the profile. A percentage of a city is a number, not a reason to go outside, and nothing was put in its place on purpose. The board of squares in the profile stays, because that one is a picture rather than a score'],
    ],
  },
  {
    version: '0.43.0',
    date: '2026-08-21',
    title: 'Three maps: the photograph, the drawing, the model',
    changes: [
      ['changed', 'The walking screen keeps three maps and nothing else. Satelita, which it now opens on, Minimal, our grey drawing, and Rzezba terenu, the photograph standing up on raised ground, always seen from an angle. Domyslny, Klasyczna, Zywa, Ciemna, Topograficzna and National Geographic are gone, and anything saved from them lands on the photograph'],
      ['added', 'Rzezba terenu carries the same name here as in a replay because it is the same thing: real elevation pushed a little, the city extruded, the camera held at an angle. It is the expensive one by nature, which is why it is a choice rather than the default'],
      ['fixed', 'Terrain written into a style comes out blank when that style is swapped in, and only works when the map is built with it. The raised map now gets its ground once the style can take it, which is why it draws at all'],
    ],
  },
  {
    version: '0.42.1',
    date: '2026-08-21',
    title: 'Changing the map is instant again',
    changes: [
      ['fixed', 'Changing the base map dragged the whole app down. Rebuilding what Parkove draws on top only checked whether it had already run two awaits later, so every styledata event during a style load, and there are many, started its own full rebuild in parallel. Drawing the pin artwork alone is 318 ms of canvas work, times all of those, on the phone that follows your walk'],
      ['fixed', 'The parks, pins and walk used to come back only once every tile in view had loaded. They are back in about 150 ms now, measured across the imagery, the dark style and the topographic one'],
      ['changed', 'Pin artwork is drawn once and kept until the theme changes, and stamp pictures are fetched once, misses included, instead of going back to the network on every change of map'],
    ],
  },
  {
    version: '0.42.0',
    date: '2026-08-21',
    title: 'The start screen gets its speed back',
    changes: [
      ['changed', 'Widok 3D is gone from the start screen. On a map that runs all day and follows a GPS fix it cost three things at once: elevation tiles, a second set of vector tiles for the buildings, and a perspective recomputed every frame. A replay can afford that for a few minutes, the map you walk with cannot'],
      ['changed', 'Eight bases stay in the picker, and 3D stays where it earns its keep: in a replay, where Rzezba terenu raises the ground three times over'],
    ],
  },
  {
    version: '0.41.1',
    date: '2026-08-21',
    title: 'Relief means the photograph on raised ground',
    changes: [
      ['changed', 'Rzezba terenu is the satellite picture draped over ground at three times its height, and its night twin is the same picture graded cold. The topographic drawing stays available as a base on the start screen'],
      ['fixed', 'Switching a look left the walk without its route, marker and pins for ten seconds or more. The route was waiting for every last tile in view, when all it needed was the style itself'],
    ],
  },
  {
    version: '0.41.0',
    date: '2026-08-21',
    title: 'Three looks, a blue walker, and a memory that closes properly',
    changes: [
      ['changed', 'A replay offers three looks now and nothing else: Rzezba terenu, which it opens on, the same relief graded for night, and Grafit 3D. The imagery, the sepia and the rest are gone from here'],
      ['changed', 'The walker is the classic blue puck with a white ring. In green it read as one more stop on the route'],
      ['changed', 'The camera holds the walker higher up the screen, so a photo or a note arriving from below no longer lands on top of it'],
      ['changed', 'The dial and the time above it sit 24 points lower'],
      ['fixed', 'Closing a photo, note or recording opened during a replay used to close the replay with it and drop you on the walk screen. Both close buttons live in the same corner, so one tap could reach the second one as the first disappeared'],
      ['fixed', 'Two memories saved in the same millisecond shared an id, and then one of them could never be edited or deleted'],
      ['fixed', 'No more Notatka label above a note in the viewer'],
    ],
  },
  {
    version: '0.40.0',
    date: '2026-08-21',
    title: 'Pick a map from the map, and stand it up in 3D',
    changes: [
      ['added', 'The look of the map is now switched from the map itself, from a button above the locate one, so two basemaps can be compared where it matters instead of from inside a settings screen'],
      ['added', 'Two more bases: Topograficzna, which is a real topographic map with contour lines and paths, and National Geographic, which is a painting'],
      ['added', 'Widok 3D is a switch rather than a style: raised ground, shading, extruded buildings and a camera that stays tilted, laid over whichever base is showing, imagery or drawing alike. It survives changing the base and it is remembered'],
      ['changed', 'A replay now opens on the topographic look with the ground pushed to three times its height, because a map of the ground may as well be a model of it'],
      ['fixed', 'Tapping a park still works with the ground raised'],
    ],
  },
  {
    version: '0.39.0',
    date: '2026-08-20',
    title: 'Four more ways to look at a walk',
    changes: [
      ['added', 'Rzezba terenu: the ground is really raised now, from free elevation tiles, and lit from the side. Piltza is flat so it barely shows there; on Kopiec Krakusa, Zakrzowek or the river valley it does'],
      ['added', 'Czarno-biala and Sepia: the imagery graded like film, so nothing on screen is green except your walk'],
      ['added', 'Mieta 3D: the whole city painted in the colours of the app, buildings included'],
      ['changed', 'Photos that pop up during a replay are a quarter smaller, so they sit on the map instead of covering it'],
      ['changed', 'The tinted inserts went back to grey'],
      ['fixed', 'A heavy look could arrive without the route, the marker and the pins: the map is now checked once more the moment it settles'],
      ['fixed', 'The white band above the home indicator, again: the screen is measured rather than asked for, every layer is pinned to both edges, and the document behind a dark screen is dark too'],
      ['fixed', 'No more scrollbar sliding in over the app while a panel scrolls'],
    ],
  },
  {
    version: '0.38.0',
    date: '2026-08-20',
    title: 'Ticks that dissolve, and a screen that ends where the screen ends',
    changes: [
      ['changed', 'Tinted inserts are back: the question a place asks and the stat cards sit on a whisper of lime instead of grey'],
      ['fixed', 'The dial ticks now really dissolve towards the arc. The fade is drawn inside the dial itself, around the same centre the ticks radiate from, instead of a mask that guessed its radius from the corner of the box'],
      ['fixed', 'Every full screen layer is now as tall as the physical screen, not as tall as the viewport the browser admits to, which is what kept leaving a white band above the home indicator'],
      ['fixed', 'Grafit 3D lost the route, the marker and the pins: one failed repaint used to lock the map out of ever drawing them again'],
      ['fixed', 'Closing a memory opened from a replay no longer drops you two screens back'],
    ],
  },
  {
    version: '0.37.0',
    date: '2026-08-20',
    title: 'A voice note on nothing but blur',
    changes: [
      ['changed', 'A voice note full screen lost its panel: the wave sits in the middle of the blurred backdrop, the play button underneath it and the caption below that, all centred'],
      ['changed', 'The photo carousel in the profile no longer fades its edges, and its prints came down a little'],
      ['fixed', 'The stacked wave had no height: in a column the flex grow was eating it'],
    ],
  },
  {
    version: '0.36.1',
    date: '2026-08-20',
    title: 'Prints a touch smaller',
    changes: [
      ['changed', 'Polaroids in the profile carousel and in the deck of a walk came down a little; the one that arrives during a replay keeps its size'],
    ],
  },
  {
    version: '0.36.0',
    date: '2026-08-20',
    title: 'A deck you push through',
    changes: [
      ['changed', 'Swiping the photos of a walk now behaves like a real deck: whichever print reaches the middle comes to the front, straightens up and grows by five percent, while the ones leaving lean back into the pile'],
    ],
  },
  {
    version: '0.35.0',
    date: '2026-08-20',
    title: 'Fading ticks and a proper player everywhere',
    changes: [
      ['changed', 'The dial ticks are longer, thinner and denser, and they fade away along their own length as well as at the ends: they dissolve into the arc instead of stopping at it'],
      ['changed', 'Every voice note now uses our own player, waveform and all. The bare system control that showed up in the full screen viewer and in the walk sheet is gone'],
      ['changed', 'The walk card gives its title twenty more points of room below the white edge'],
    ],
  },
  {
    version: '0.34.0',
    date: '2026-08-20',
    title: 'Open a memory, and no more white strip',
    changes: [
      ['added', 'A memory in a replay can be tapped: photos, recordings and notes open full screen and can be swiped through, and a point opens its whole story. The walk stops while you read'],
      ['fixed', 'The white band at the bottom of the installed app is gone. The map now runs past the bottom edge, under the home indicator, instead of stopping at it and letting the white page show through'],
    ],
  },
  {
    version: '0.33.1',
    date: '2026-08-20',
    title: 'Bigger prints',
    changes: [
      ['changed', 'Polaroids are about a third larger and a little rounder, both in the deck and when one arrives during a replay'],
    ],
  },
  {
    version: '0.33.0',
    date: '2026-08-20',
    title: 'Three ways to see a walk',
    changes: [
      ['added', 'A button top right of a replay changes how the ground looks: Satelita as it is, Noc where the imagery is graded cooler and darker like film, and Grafit 3D which drops the photos and paints the city from our own palette with the buildings still standing up'],
      ['changed', 'The memory no longer announces itself with a heading: a photo is a photo, a note is a note'],
      ['fixed', 'Map credits moved under the darkness at the bottom, out of the picture'],
      ['fixed', 'Switching the look used to lose the route, the marker and the pins: several repaints raced each other, and now only one runs'],
    ],
  },
  {
    version: '0.32.1',
    date: '2026-08-20',
    title: 'Yellow paper, smaller hand',
    changes: [
      ['changed', 'A sticky note is canary yellow now, and a long note writes itself smaller instead of growing the paper'],
      ['changed', 'The walk clock reads at the size of its own label, in white: a readout rather than a headline'],
    ],
  },
  {
    version: '0.32.0',
    date: '2026-08-20',
    title: 'Tap a pin, walk there',
    changes: [
      ['added', 'Pins in a replay are tappable: the walker sets off, covers the ground and lands softly at that place, then the memory speaks. The dial lets go while it travels, and touching the dial cancels the trip'],
      ['changed', 'A note is a sticky note again: rounded paper in a marker hand, dropped slightly crooked, arriving like something being put down'],
      ['changed', 'Pins in a replay wear a white edge with a slightly smaller mark inside, and the blur under the memory is lighter'],
    ],
  },
  {
    version: '0.31.1',
    date: '2026-08-20',
    title: 'A little more darkness',
    changes: [
      ['changed', 'The shadow under a replay reaches higher and lets go more slowly, so the map fades into it instead of meeting an edge'],
    ],
  },
  {
    version: '0.31.0',
    date: '2026-08-20',
    title: 'Pause, and the handle springs home',
    changes: [
      ['added', 'A pause button under the arc. It brings the handle back to the middle with a spring rather than a jump, overshooting the centre by a hair before it settles'],
      ['changed', 'The hour a memory was left and the speed multiplier are gone from the replay: the walk clock is enough'],
    ],
  },
  {
    version: '0.30.2',
    date: '2026-08-20',
    title: 'Centred, and one family of greens',
    changes: [
      ['changed', 'Everything under a replay is centred now, and the walk clock reads as one line: the number, then its label'],
      ['changed', 'The dial ticks fade twice over: out to both ends, and inwards towards the centre of the circle, so each tick is brightest at its outer tip'],
      ['changed', 'Pins, the marker and the dial handle share three colours with the walked line, so they read as one family instead of three'],
    ],
  },
  {
    version: '0.30.1',
    date: '2026-08-20',
    title: 'Pins and ticks, to the reference',
    changes: [
      ['changed', 'Pins in a replay have their own look: a dark green disc with a lime edge and a lime mark inside, photos as a circle in a white ring, and the walked line in a brighter green'],
      ['changed', 'The dial ticks are thin and fade out at both ends under a shadow, the way a real dial reads. The handle keeps its own light, with four white dots'],
      ['changed', 'The walk clock is half the size again, so the map keeps the attention'],
    ],
  },
  {
    version: '0.30.0',
    date: '2026-08-20',
    title: 'The dial, drawn properly',
    changes: [
      ['changed', 'The throttle became an arc of rounded ticks across the bottom of the screen, dragged sideways, with the ticks lighting up in lime behind the handle. The handle is a dark green pill with a lime edge and four dots, riding the arc and tilting with it'],
      ['changed', 'Speed no longer snaps: asking for a faster walk spins it up over about half a second, and letting go lets it coast down. The number next to the clock shows it building'],
      ['changed', 'The bottom of the replay reads in one column now: the memory, then the walk clock right aligned in mono, then the dial'],
      ['changed', 'The top of a replay is just the way out. The title, the gradient and the blur under it are gone, so nothing sits between you and the ground'],
      ['fixed', 'A drag that could not capture the pointer used to die silently; sheets and the dial now carry on without it'],
    ],
  },
  {
    version: '0.29.1',
    date: '2026-08-20',
    title: 'The clock reads like an instrument',
    changes: [
      ['changed', 'The walk clock in a replay sits above the darkness now, half the size, set in JetBrains Mono, with the map credits moved out of its way'],
      ['changed', 'No more "end of route" line: the label under the clock only says what the throttle is doing'],
    ],
  },
  {
    version: '0.29.0',
    date: '2026-08-20',
    title: 'Arriving somewhere feels like arriving',
    changes: [
      ['added', 'A replay now slows down as it comes up to something you left behind, and stands still for a beat when it lands. A voice note starts playing by itself: you walked up to it, so it speaks'],
      ['changed', 'Memories have no close button any more. There is always one on screen, and it changes when you reach the next'],
      ['changed', 'The darkness under a memory goes deeper and higher, with the same progressive blur as the header, so the map dissolves into it instead of being covered'],
      ['changed', 'The camera rides higher on the screen, above the darkness, and a written note is a rounded sticky note lying a little crooked'],
    ],
  },
  {
    version: '0.28.0',
    date: '2026-08-20',
    title: 'Squircles, and memories without a frame',
    changes: [
      ['changed', 'Buttons and controls left the pill behind: they are 16 px rounded squares with iOS style corner smoothing, and so are the cards on the profile and in the walks'],
      ['changed', 'A memory during a replay has no card any more. It arrives on a soft darkness at the bottom of the screen: a small label, a photo dropped like a polaroid, or your own words in your own hand'],
      ['changed', 'The header of a replay floats on a progressive blur, four bands deep, with a gentle gradient under it'],
      ['added', 'Voice notes are drawn as their own waveform, read from the recording itself, filling in with lime as it plays. While recording, the bars move with your voice next to a big clock'],
    ],
  },
  {
    version: '0.27.0',
    date: '2026-08-20',
    title: 'White paper, deep green, one lime',
    changes: [
      ['changed', 'The palette moved to white paper with truly neutral greys: a tinted grey reads as dirt next to white, so the tint is gone'],
      ['changed', 'Green went deep, almost black, and lime arrived as the one loud voice: it writes on the dark green fills, never on white'],
      ['changed', 'Gold now belongs to the collection alone, so notes are written on paper and voice pins wear the deep green with a lime microphone'],
    ],
  },
  {
    version: '0.26.0',
    date: '2026-08-20',
    title: 'The walk card behaves like a card',
    changes: [
      ['fixed', 'Opening a walk now frames the whole route in the part of the map you can actually see, above the card'],
      ['fixed', 'Pulling the card down no longer throws you back to the start. It settles at its smallest size, showing the name and the button that replays the walk'],
      ['changed', 'That card lost its grabber: it belongs to the screen, so it should not look like something you can dismiss. The rename control became a proper icon button, the same size as every other one'],
      ['changed', 'Photos of a walk lie in a deck now: overlapping, each a little crooked, and touching one straightens it and lifts it out of the pile. Their shadows have room instead of being cut off'],
      ['fixed', 'A point opened from a walk came out dimmed and shifted, because it inherited the dimming of the screen underneath. Screens are now mounted at the top of the page, so nothing tints them'],
    ],
  },
  {
    version: '0.25.0',
    date: '2026-08-20',
    title: 'Full height, and one size for rows',
    changes: [
      ['fixed', 'The app no longer slides under a strip at the bottom. It was measured against the largest possible viewport instead of the visible one, which turned the whole app into a scrolling page and cut the content off. Screens now fill exactly the height you can see'],
      ['changed', 'A sheet keeps its actions in a bar stuck to the bottom: one wide button and the dangerous things beside it. Moving a pin became a small button under the title, where it belongs'],
      ['fixed', 'List rows had two different title sizes depending on whether they carried a sentence. One size everywhere now'],
      ['added', 'DS: ActionBar, the sticky row of actions, with its own page in the catalog'],
    ],
  },
  {
    version: '0.24.0',
    date: '2026-08-20',
    title: 'Screens that move like a phone',
    changes: [
      ['changed', 'Screens now arrive the way phones do it. Something presented over your work rises from the bottom: the profile, the walk summary, a screening. Going a level deeper slides in from the right: a stamp, a walk, a point, the settings'],
      ['changed', 'While a screen is pushed on top, the one below slides aside and dims a little, so back has somewhere to go back to'],
      ['changed', 'All of it on one curve, the one iOS uses for sheets: quick to leave, slow to land, no bounce. Anyone who asked their phone for less motion gets none'],
    ],
  },
  {
    version: '0.23.1',
    date: '2026-08-20',
    title: 'Smoother, faster replays',
    changes: [
      ['changed', 'The camera now aims a little up the route and turns towards it gradually, so a corner reads as turning your head instead of a cut'],
      ['changed', 'The throttle goes much further: the top of the dial skims a whole walk in under a minute, while the lower half stays fine enough to creep along'],
      ['fixed', 'The walk clock had grown into the dial below it; they share a right edge now, with room between them'],
      ['changed', 'Stat cards put the icon above the number, so a two word value like "40 min" no longer breaks across lines'],
    ],
  },
  {
    version: '0.23.0',
    date: '2026-08-20',
    title: 'Walk it again',
    changes: [
      ['added', 'Memories mode: from a walk in the journal you can walk the same route again. Satellite imagery, a tilted camera and extruded buildings, your past self moving along the line, and a throttle in the corner: push it up to go, further to go faster, below the middle to walk backwards'],
      ['added', 'Photos, recordings, notes and points arrive as you reach the places they were left at, with the walk clock running next to them'],
      ['added', 'Tapping a photo, a recording or a note opens it full screen over a blurred backdrop, and you swipe between them like a stack of slides. Captions can be written there, and pins moved or deleted'],
      ['changed', 'The replay paces itself between the moments we actually know: the start, the end, and the minute each point was reached'],
    ],
  },
  {
    version: '0.22.0',
    date: '2026-08-20',
    title: 'A profile with room to breathe',
    changes: [
      ['changed', 'The profile header drops the ring for the city as a board: one square per place, filled in as you walk, with the percentage in full size next to it'],
      ['changed', 'Stamps, walks and kilometres are three cards with icons, and every section on the page has twice the room it had'],
      ['added', 'Tapping a stamp opens its own page: where it comes from, when you first stood there, points, visits and the photos you took in that park'],
      ['changed', 'The walk screen header is transparent with no label, and its back button is white so it reads over any map'],
      ['added', 'DS: StatGrid does three columns, Stamp can be tapped, NavBar has a transparent variant'],
    ],
  },
  {
    version: '0.21.0',
    date: '2026-08-20',
    title: 'The walk screen behaves',
    changes: [
      ['changed', 'A walk from the journal is now its route on a full screen with the details in a sheet over it: pull the sheet down to look at the map, up to read everything'],
      ['fixed', 'Photos, recordings, notes and points opened behind the walk screen, on the live map. They open inside it now, and a point can be read again with its whole story'],
      ['changed', 'Photos of a walk are a plain carousel like in the profile, with no white fade at the edges and a wider gap on the left'],
      ['changed', 'The plus menu sits 24 px above the bar, its buttons are closer together, and they rise and sink one after another'],
    ],
  },
  {
    version: '0.20.0',
    date: '2026-08-20',
    title: 'One plus instead of three icons',
    changes: [
      ['changed', 'The walk bar carries a single plus now. It opens three primary buttons, each only as wide as its label: add a photo, add a recording, add a note'],
      ['changed', 'Recording moved into its own sheet with a big microphone: hold it, talk, let go, then keep it or record again'],
      ['fixed', 'The map takes the full height of the screen on a phone, instead of stopping short of the home indicator'],
    ],
  },
  {
    version: '0.19.1',
    date: '2026-08-20',
    title: 'No white line at the bottom',
    changes: [
      ['fixed', 'The strip behind the home indicator went white after the status bar fix. It belongs to the document, so it now carries the app background instead of the browser default'],
    ],
  },
  {
    version: '0.19.0',
    date: '2026-08-20',
    title: 'Walk history on its own screen',
    changes: [
      ['changed', 'A walk from the journal now opens as its own screen with its own map of the route, instead of a sheet over the live map. Looking back no longer tangles with where you are now'],
      ['added', 'A location button on the map, quiet in the corner: it shows where you are outside a walk too, and during one it puts the camera back on you'],
      ['added', 'Photos, recordings and notes are tappable straight on the route map of a past walk'],
    ],
  },
  {
    version: '0.18.2',
    date: '2026-08-20',
    title: 'Map right up to the top',
    changes: [
      ['fixed', 'The band under the clock and battery is gone: iOS was painting that strip with the theme colour, and a gradient of ours sat on top of it. The map now runs to the very edge of the screen'],
    ],
  },
  {
    version: '0.18.1',
    date: '2026-08-20',
    title: 'Stats that can breathe',
    changes: [
      ['changed', 'Walk stats are cards in two columns now, each with its own icon, instead of four numbers crammed into one line'],
      ['added', 'DS: Stat takes an icon and StatGrid lays the cards out; both are in the catalog'],
      ['fixed', 'The notes list had slipped inside the stats block in the walk sheet'],
    ],
  },
  {
    version: '0.18.0',
    date: '2026-08-20',
    title: 'Voice, notes and a proper ending',
    changes: [
      ['added', 'Voice notes: hold the microphone, let go, listen back, then decide whether it stays. Saved ones become pins on the route'],
      ['added', 'Written notes pinned to a place, in a travelling hand, for things like the sunset that happened right here'],
      ['added', 'Ending a walk is now a small ceremony: the stamp first, then a summary of what the walk added up to, then it lands in the history'],
      ['added', 'The summary shows the badge even when it was not earned: pale, locked, and with the exact points still missing'],
      ['added', 'The journal remembers the hour each point was reached, and lists the notes and recordings from that walk'],
      ['added', 'A new test route along Piltza, from 43 to 34: six points, half a kilometre, from a block named Brussels to the doctor the street is named after, with the Kobierzyn memorial in between'],
      ['changed', 'The drawn track is calmer: readings that imply running are dropped and the rest is smoothed, weighted by how sure the GPS is'],
      ['changed', 'A full set of points no longer reads like the end of the walk. It says so, and leaves the decision to you'],
      ['changed', 'Polaroids are rounder, and a photo without a caption simply has none'],
    ],
  },
  {
    version: '0.17.1',
    date: '2026-08-20',
    title: 'Notices a new version',
    changes: [
      ['added', 'The app checks whether a newer build is live and offers a refresh, because an installed app on iOS tends to resume the old page instead of loading the new one. Never during a walk: a reload would lose it'],
    ],
  },
  {
    version: '0.17.0',
    date: '2026-08-20',
    title: 'Walks you can come back to',
    changes: [
      ['added', 'Every past walk opens from the profile: its route lands on the map and a sheet holds the details, so you can look at where you actually went'],
      ['added', 'Past walks are editable. Rename them, write a note at home, add photos from the camera roll later, move or delete their pins, or drop the whole walk from the journal'],
      ['changed', 'The profile lists all your walks now, not just the last three, and shows the name you gave them'],
      ['fixed', 'Taking a photo no longer opens a system prompt for the caption. That dialog could freeze the installed app; the caption is written in the photo sheet instead'],
      ['fixed', 'A name or note typed into a sheet survives closing it by dragging, which never fired the save before'],
    ],
  },
  {
    version: '0.16.0',
    date: '2026-08-20',
    title: 'Photos on the route, and a proper goodbye',
    changes: [
      ['fixed', 'The stamp no longer lands the moment a walk starts. It is now the reward for a finished park: every point collected, handed over once you close the walk'],
      ['fixed', 'Photos and stamps were being asked for from the root of the domain, so on the phone nothing loaded. Every file now goes through the base path of the build'],
      ['added', 'Ending a walk asks first, and shows what you are about to save. Points the GPS missed can be ticked by hand there, before the walk becomes a journal entry'],
      ['added', 'A photo taken on a walk becomes a pin where you stood, as a round thumbnail. Tap it to caption it, move it or delete it. Those pins stay inside the walk, off the everyday map'],
      ['added', 'A start button on the peek card, but only when you are actually near the park (300 m). Too far, no button'],
      ['changed', 'Taking a photo while walking no longer stops to ask for a caption: it saves, and offers to describe it afterwards'],
    ],
  },
  {
    version: '0.15.0',
    date: '2026-08-20',
    title: 'A walk you can see',
    changes: [
      ['added', 'Your position on the map: a dot with a circle showing how sure the GPS is, and the camera rides along until you touch the map (then a button brings it back)'],
      ['added', 'The top card turns into the live walk: a ring of the points on this walk, its name, a pulse, and which way the next point is with the distance'],
      ['added', 'Two-stage detection: a soft buzz around 50 m to make you look around, and the point counts once you are really there (15 m, or as close as the GPS can promise)'],
      ['added', 'Arriving now shows a notice with "Czytaj" instead of taking over the screen: the point is already counted, the story can wait for a bench'],
      ['added', 'A tick on collected pins, so a walked route reads at a glance'],
      ['added', 'New DS component: Toast, the non-modal notice used for both of those'],
      ['changed', 'The bottom bar slimmed down to what the thumb needs: camera, time and distance, end of walk'],
      ['changed', 'The drawn path drops readings vaguer than 30 m and marks gaps (phone asleep, signal lost) with a dashed line instead of a made-up shortcut'],
      ['changed', 'Walks get names like "Ruczaj, czwartek wieczorem", so the journal reads like a diary'],
    ],
  },
  {
    version: '0.14.1',
    date: '2026-08-20',
    title: 'Full screen on iOS',
    changes: [
      ['fixed', 'The installed app no longer paints a white bar over the top of the map: the map now runs under the status bar, with a soft gradient so the clock stays readable'],
    ],
  },
  {
    version: '0.14.0',
    date: '2026-08-20',
    title: 'Installable and offline',
    changes: [
      ['added', 'The app is now a real PWA: add it to the home screen and it opens like an app, full screen, with its own icon'],
      ['added', 'A service worker keeps the app, the photos and the map tiles you have already seen, so a park with no signal (or a dead dev server) no longer breaks it'],
      ['added', 'Deploy to GitHub Pages on every push, so the phone always has a stable HTTPS address instead of a laptop on the local network'],
    ],
  },
  {
    version: '0.13.1',
    date: '2026-08-20',
    title: 'Test ground on Ruczaj',
    changes: [
      ['added', 'A test area around Piltza 43 with three points: the doorway, the Allegro locker 90 m away and Stokrotka 150 m away, so an expedition can be tried from home'],
      ['added', 'One command removes the test area when the field test is done: npm run test-park:remove'],
    ],
  },
  {
    version: '0.13.0',
    date: '2026-08-20',
    title: 'Light by default, 37 parks with a game',
    changes: [
      ['changed', 'The app opens in light mode by default; auto and dark stay one tap away in settings'],
      ['added', 'Eleven more quests: Stacja Wisla with an installation by Miroslaw Balka, Grzegorzecki and Reduta with Fortress Krakow remains, Witkowice with a hidden cavern, Szymborskiej, Zaczarowanej Dorozki, Laki Nowohuckie, Duchacki, Przylasek Rusiecki, Aleksandry and Zielony Jar'],
      ['added', 'The collection reaches 115 points across 37 parks, with 103 questions'],
      ['fixed', 'Estimated point positions were pulled inside park boundaries; real objects just outside got a matching reach'],
      ['added', 'If the app ever crashes it now shows a way out instead of freezing on the last frame: one tap reloads and the progress stays'],
    ],
  },
  {
    version: '0.12.0',
    date: '2026-08-20',
    title: 'Field games in 26 parks',
    changes: [
      ['added', 'Eleven more quests: Kopiec Kosciuszki, Jerzmanowskich, Bagry, Wyspianskiego, Solvay, Mlynowka, Panienskie Skaly, Jalu Kurka, Wisniowy Sad, Planty Bienczyckie and Park Szwedzki'],
      ['added', 'Planty grew to ten points, including Collegium Novum and the arrest of the professors, Zuzanna Ginczanka and the theatre built on a demolished monastery'],
      ['added', 'The collection now holds 104 points in 26 field games, with 81 questions to argue about'],
      ['fixed', 'Points that stand just outside a park (churches, palaces) got a reach that matches where they really are'],
    ],
  },
  {
    version: '0.11.0',
    date: '2026-08-20',
    title: 'Ten more field games',
    changes: [
      ['added', 'Ten new quests: Planty, Las Wolski, Park Krakowski, Strzelecki, the Botanic Garden, Lotnikow, Bednarskiego, Blonia, Kopiec Wandy and Decjusza'],
      ['added', '32 new points, each with a public story, a reveal unlocked on site and a question to argue about on the bench'],
      ['added', 'The city now holds 82 collectible points across 15 field games, up from 55 and five'],
      ['fixed', 'Three points sat outside their park boundary and were moved inside, so they can be collected on a walk'],
      ['changed', 'Photos shrunk for phones: the app build dropped from 83 MB to 29 MB with no visible loss'],
      ['fixed', 'The Banach monument photo was a 348 px thumbnail, replaced with a sharp one'],
    ],
  },
  {
    version: '0.10.0',
    date: '2026-08-20',
    title: 'Every park has a story',
    changes: [
      ['added', 'All 48 places now have a written page: what it is, why go, and what makes it different from the park next door'],
      ['added', 'Food and playgrounds for 40 parks straight from OpenStreetMap, curated to the six closest named places and four playgrounds'],
      ['added', 'Photos for the park pages, pulled from Wikimedia Commons with credits'],
      ['fixed', 'Pin positions verified against park boundaries: two quest points sat outside their park and were moved in'],
    ],
  },
  {
    version: '0.9.0',
    date: '2026-08-20',
    title: 'Profile with your own trail',
    changes: [
      ['added', 'Profile is a full screen now: a greeting with your name, the city ring, stamps, photos, recent walks and one nudge where to go today'],
      ['added', 'Walk photos: take one during a walk, add a note, and it lands in the profile as a polaroid with park and date'],
      ['added', 'Polaroid component and photo storage that keeps pictures on the device (IndexedDB)'],
      ['added', 'Your name lives in the profile: tap the greeting to change it, the initials become your avatar'],
      ['changed', 'Settings moved off the profile into two pages of their own: app appearance and map look'],
      ['added', '"Where to today": one unvisited park suggested each day, quest parks first'],
    ],
  },
  {
    version: '0.8.0',
    date: '2026-08-20',
    title: 'Stamps and icon pins',
    changes: [
      ['added', 'Park stamps: a sticker per park, pale until you collect it, with a full-screen celebration the moment it lands'],
      ['added', 'Collection screen in the profile: every stamp in one grid with a counter'],
      ['added', 'Stamp on the park hero, like a mark in a passport'],
      ['added', 'Stamp pins appear on the map for collected parks once you zoom in, and tapping one opens that park'],
      ['added', 'Quest pins carry category icons in the app icon style: view, monument, water, nature, cave, history, meadow, climb'],
      ['added', 'Slicing script: drop a sticker sheet in assets-in/ and npm run stamps cuts one transparent PNG per park'],
      ['fixed', 'Pins were unclickable: the map click handler held stale callbacks and the park polygon under the pin always won'],
      ['changed', 'More air between park page sections, especially around the point carousel and the amenity rows'],
      ['added', 'First ten stamps are in: the sticker sheet was sliced into transparent PNGs and they already show on the map'],
      ['added', 'Practical pins have their own colours: parking in blue, food in amber, playgrounds in magenta, all generated from the HCT seed'],
      ['added', 'Food and playground spots from OpenStreetMap; tapping a pin or the amenity row opens the list with walking directions'],
      ['changed', 'Stamp celebration darkens and blurs the background much harder, so only the sticker matters'],
    ],
  },
  {
    version: '0.7.1',
    date: '2026-08-19',
    title: 'Park page redesign',
    changes: [
      ['changed', 'Park page follows the new draft: a full-bleed hero photo with the name written on it, swipeable photos with dots, then progress and a folded description'],
      ['added', 'MediaHero component: header image carousel with title overlay, dots and per-photo credit'],
      ['added', 'Collapsible component: long copy folded to a few lines with a "Więcej" toggle'],
      ['added', 'Sheets support a hero slot: media runs to the panel edges and the handle floats over it'],
      ['changed', 'Unfolding a description glides open instead of snapping, and the last folded line fades out'],
      ['changed', 'Photo credit left the header image; attribution now sits quietly at the bottom of the park page'],
      ['changed', 'Amenities are proper rows now: icon, small heading and a sentence, separated by hairline dividers instead of pills'],
      ['added', 'List component: wraps rows with hairline dividers inset past the icon; the parks list and parking list use it too'],
      ['added', 'Public transport row under parking: the nearest stop and its lines, tapping it opens Google Maps transit directions from wherever you are'],
    ],
  },
  {
    version: '0.7.0',
    date: '2026-08-19',
    title: 'Questions, park pages, Skałki and Skawina',
    changes: [
      ['added', 'Every point can now ask a question: after the reveal you pick a side and the app argues the other one'],
      ['added', 'Dilemmas written for 11 points, from digging up a 1200-year-old mound to a bear who never chose the war'],
      ['added', 'Park page: hero photo, gallery, "why go there" description and the two amenities that decide a family Saturday (playground, food)'],
      ['added', 'New quest: Skałki Twardowskiego with the sorcerer legend, the cave and the climbing walls'],
      ['added', 'New park with a quest: Park Miejski in Skawina (the collection now reaches beyond Kraków)'],
      ['added', 'Photos for twelve points, all CC from Wikimedia Commons with credits'],
      ['changed', 'Zakrzówek keeps four points; the Skałki now live in their own quest'],
    ],
  },
  {
    version: '0.6.1',
    date: '2026-08-19',
    title: 'Feel and polish',
    changes: [
      ['added', 'Peek card has a "Zobacz szczegóły miejsca" button under the dots'],
      ['changed', 'More room to breathe in the peek card and in sheet headers'],
      ['changed', 'Top bars keep their size and turn translucent with a progressive blur once content scrolls under them'],
      ['changed', 'Segmented control: the raised pill now glides between options instead of fading in place'],
      ['changed', 'Changelog reads more clearly: version and date in one row, wider line spacing, aligned type tags'],
      ['fixed', 'Sheet header blur no longer bleeds the page behind the panel (layer isolation)'],
      ['fixed', 'Pinch zoom disabled in the app and the catalog, so the catalog behaves like part of the app'],
    ],
  },
  {
    version: '0.6.0',
    date: '2026-08-19',
    title: 'Live map interaction',
    changes: [
      ['added', 'Peek card: tapping a park on the map opens a compact floating card; pins stay clickable, drag up expands to the full sheet'],
      ['added', 'Tapping a quest pin swaps the peek to that point: photo, teaser and a tap-through to the full story'],
      ['added', 'Parking pin (P) on the map for the suggested spot; tapping opens a full-screen list of suggestions with navigation'],
      ['added', 'NavBar component: X or back always on the left, centered title; used by modals and the mobile catalog'],
      ['added', 'Back-to-app nav bar in the catalog on mobile'],
      ['changed', 'The park sheet is non-modal now: no dimming, the map stays live; tapping empty map closes the peek'],
      ['changed', 'Modal header uses NavBar: action on the left, title centered'],
      ['changed', 'Carousel cards fade out at the screen edge instead of a hard crop'],
      ['fixed', 'Carousel cards align to the top edge; a shorter caption no longer floats its photo upward'],
      ['fixed', 'Tapping a park area on the map did nothing: string feature ids need promoteId in MapLibre; visited park colors relied on it too'],
      ['added', 'Peek swipe pages: park, quest points and parking in one card; content slides with the finger, dots show the position'],
      ['added', 'The active page highlights its pin on the map and the camera flies to it'],
      ['added', 'Profile links to the design system catalog'],
    ],
  },
  {
    version: '0.5.1',
    date: '2026-08-19',
    title: 'Sheet polish, default and satellite map',
    changes: [
      ['changed', 'Sheet headers no longer cut content with a solid edge: scrolled content slides underneath and fades out in a gradient with a progressive blur'],
      ['added', 'Map style "Domyślny": follows the app theme (Minimal in light, Ciemna in dark) and is the new default'],
      ['added', 'Map style "Satelita": Esri World Imagery with lighter park fills so the greenery shows through'],
      ['changed', 'Park sheet breathes: more space between sections, the point carousel sits within the margins'],
      ['fixed', 'Park meta line was caught in the header fade zone right after opening'],
      ['changed', 'Point modal hardened to truly full screen, above every sheet'],
    ],
  },
  {
    version: '0.5.0',
    date: '2026-08-19',
    title: 'Profile, map styles and polish',
    changes: [
      ['added', 'Profile (top right): app theme switch (auto, light, dark) shared with the catalog'],
      ['added', 'Four map styles switchable in the profile with a live preview: Minimal, Klasyczna, Żywa, Ciemna'],
      ['added', 'Point details open as a full-screen modal with a gentle enter, photos and the whole story'],
      ['added', 'Quest points in the park sheet are a snap carousel of cards instead of a plain list'],
      ['added', 'Suggested parking per pilot park: a concrete spot and fee hint (OSM-checked)'],
      ['added', 'DS components: Modal, Carousel, Segmented (the catalog theme switch now uses it too)'],
      ['fixed', 'Sheets animate out on close (drag, scrim, Escape) instead of vanishing in one frame'],
    ],
  },
  {
    version: '0.4.0',
    date: '2026-08-19',
    title: 'Point cards and the iOS sheet',
    changes: [
      ['added', 'Point card: tap any quest point (list, map, or Read more) for photos and the full story, anytime'],
      ['added', 'Rich public descriptions for all 12 pilot points; the hidden on-site reveal stays as the punchline'],
      ['added', 'CC photos from Wikimedia Commons for five points, stored locally with attribution'],
      ['added', 'Walk journal: every expedition saves its track, distance, time and collected points'],
      ['added', 'Compass on the expedition bar: distance and direction to the nearest remaining point'],
      ['changed', 'BottomSheet rebuilt iOS-style: two detents (auto and full), drag anywhere, inner scroll only at full'],
      ['changed', 'Selecting a park flies the map to it with the sheet in mind, so the park is not covered'],
      ['changed', 'Quest dots show on the map when browsing a quest park, not only during a walk'],
    ],
  },
  {
    version: '0.3.0',
    date: '2026-08-19',
    title: 'Quests and expeditions',
    changes: [
      ['added', 'Pilot quests in three parks: Kopiec Krakusa, Zakrzówek and Park Jordana (4 points each, real OSM coordinates)'],
      ['added', 'Two-tier point content: a public teaser for planning, a hidden story revealed only on site'],
      ['added', 'Expedition mode: screen stays awake, GPS records the track (km, time) and detects points in radius'],
      ['added', 'Reveal sheet with the story, progress and a hint to the nearest remaining point'],
      ['added', 'Expedition bar with live time, distance and points; quest dots and the walked track drawn on the map'],
      ['changed', 'City progress now counts points: a quest park scores per point, a plain park scores its entry (55 points total)'],
    ],
  },
  {
    version: '0.2.1',
    date: '2026-08-19',
    title: 'Map fix and phone testing',
    changes: [
      ['fixed', 'Map never finished loading (blank page): MapLibre 6.4.1 regression, pinned to stable 5.x'],
      ['added', 'Phone testing mode: npm run dev:phone serves the app over HTTPS on the local network, so GPS works on the phone'],
    ],
  },
  {
    version: '0.2.0',
    date: '2026-08-19',
    title: 'Map foundations',
    changes: [
      ['added', 'Live map of Kraków (MapLibre) with the fog of war: visited parks in green, the rest greyed out'],
      ['added', 'Park data from OpenStreetMap: curated set of parks, mounds, woods and lakesides with real boundaries'],
      ['added', 'Park sheet with check-in: GPS verifies you are inside the park boundary'],
      ['added', 'City progress: percent of Kraków discovered, stored locally on the device'],
      ['added', 'Version history: click the version number in the catalog sidebar to open this changelog'],
      ['added', 'ListItem component for the parks list (leading disc, title, meta, trailing slot)'],
      ['changed', 'Map colors are driven by the same DS tokens in light and dark'],
    ],
  },
  {
    version: '0.1.0',
    date: '2026-08-19',
    title: 'Foundation',
    changes: [
      ['added', 'Color tokens generated from one HCT seed (forest green), light and dark from day one'],
      ['added', 'Core tokens: 4px spacing rhythm, radius, elevation, motion, control sizes'],
      ['added', 'Type roles: Bricolage Grotesque for display, Manrope for text'],
      ['added', 'Components: Button, IconButton, Chip, ParkBadge, ProgressRing, Card, ParkCard, BottomSheet, Stat'],
      ['added', 'This catalog: tokens, components and live examples with a theme switch'],
    ],
  },
]
